packages:
  - apps/*
  - packages/*

catalog:
  '@commitlint/cli': ^20.3.0
  '@commitlint/config-conventional': ^20.3.0
  '@eslint/js': 9.39.2
  '@ls-lint/ls-lint': ^2.3.1
  '@nestjs/cli': ^11.0.14
  '@nestjs/common': ^11.1.11
  '@nestjs/core': ^11.1.11
  '@nestjs/platform-express': ^11.1.11
  '@nestjs/schematics': ^11.0.9
  '@swc/cli': 0.7.9
  '@swc/core': 1.15.8
  '@types/node': ^24.10.4
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^4.7.0
  cspell: ^9.4.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  globals: ^16.5.0
  husky: ^9.1.7
  knip: ^5.79.0
  prettier: ^3.7.4
  react: ^19.2.3
  react-dom: ^19.2.3
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  stylelint: ^16.26.1
  stylelint-config-standard: ^39.0.1
  turbo: ^2.7.3
  typescript: ^5.9.3
  typescript-eslint: ^8.51.0
  vite: ^7.3.0

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
  - oxc-resolver
